### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by yakuter**

### CODE REVIEW

**Comment by mrturkmen06** [comment]
ups, too much conflict, high risk of revealing old monster.

**Comment by mrturkmen06** [comment]
Should next developments still continue from `dev` branch, btw ?

**Comment by yakuter** [comment]
> ups, too much conflict, high risk of revealing old monster if any.

@mrturkmen06 in fact this is my mistake not to define strict rules about commiting. So some of the developers send PR to master and some of them to dev.

This PR and conflicts do not worry, one of my friend working on it and merge all your 15 file changes to master. Then I will delete dev branch and continue developint on master with a clear contributing rules.

Can you wait just a little before contributing again? 

By the way, if you know any document which explains an open source project or may be management, I would like to read.

**Comment by mrturkmen06** [comment]
@yakuter 

I see, yeah that's not a problem, but wanted to point out it because having clear development cycle, branch naming policy, and preventing people who are able to push to master (without review and acceptance process) could be nice. It can be handled by repo settings, enabling [protected branches features](https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks),  it would be enough for further confusions , I guess. 

Additional [best practices](https://www.datree.io/resources/github-best-practices) post could be useful to obey. 

Regarding to open source project, this [tiny document](https://www.ibrahimatlinux.com/uploads/6/3/9/7/6397792/00.pdf) could be useful. 

For having [branch naming policy](https://gist.github.com/digitaljhelms/4287848) would be nice too. After judging which is most suitable for  [pass-wall](https://github.com/pass-wall), it could be used in wider perspective in all repositories of [pass-wall](https://github.com/pass-wall)

**Comment by yakuter** [comment]
> @yakuter
> 
> I see, yeah that's not a problem, but wanted to point out it because having clear development cycle, branch naming policy, and preventing people who are able to push to master (without review and acceptance process) could be nice. It can be handled by repo settings, enabling [protected branches features](https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks), it would be enough for further confusions , I guess.
> 
> Additional [best practices](https://www.datree.io/resources/github-best-practices) post could be useful to obey.
> 
> Regarding to open source project, this [tiny document](https://www.ibrahimatlinux.com/uploads/6/3/9/7/6397792/00.pdf) could be useful.
> 
> For having [branch naming policy](https://gist.github.com/digitaljhelms/4287848) would be nice too. After judging which is most suitable for [pass-wall](https://github.com/pass-wall), it could be used in wider perspective in all repositories of [pass-wall](https://github.com/pass-wall)

These are great sources. I will make everything clear as soon as possible. Thank you so much.

**Comment by yakuter** [comment]
Hello @mrturkmen06,

Now we have just 2 branches, Master and Stable.
I enable protected features for them.
I wrote a contribution document [here](https://github.com/pass-wall/passwall-server/blob/master/CONTRIBUTING.md). Every issues, pull requests, commits and contributions will be made according to this document. Also it will be also translated to Turkish.
By the way all your contribution is added to master branch.

I think everything will be better with these.

**Comment by mrturkmen06** [comment]
👍🏻 Wonderful !

**Pull request closed without merging**
