### PR TITLE
Removed unnecessary alpine image

### PR DESCRIPTION
**Pull request by TheYkk**
To fix this issue #108 
Removed Remove unnecessary alpine image

### CODE REVIEW

**Comment by yakuter** [comment]
@TheYkk I get the error below. Can you check it?
Screen Shot 2020-05-29 at 21 50 35

**Comment by TheYkk** [comment]
Fixed

**Comment by yakuter** [comment]
This time I have problem with my MacOS file system I think. I searched for de error and it seems this error generally occur in Windows and they fix it with dos2unix tool.
`standard_init_linux.go:211: exec user process caused "no such file or directory"`
Screen Shot 2020-05-30 at 00 52 26

**Comment by TheYkk** [comment]
@yakuter Can you check again

**Comment by yakuter** [comment]
Now it is OK. Thank you :)

**Pull request merged**
